//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由动软.Net代码生成器生成。
//     运行库版本:2.5
//
//     请根据项目的实际情况，修改该模板。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Change.Web.Orders {
    
    
    /// <summary>
    /// Show 类。
    /// </summary>
    /// <remarks>
    /// 自动生成的类。
    /// </remarks>
    public partial class Show {
        	protected global::System.Web.UI.WebControls.Label lblOrdersID;
	protected global::System.Web.UI.WebControls.Label lblOrderdate;
	protected global::System.Web.UI.WebControls.Label lblUserId;
	protected global::System.Web.UI.WebControls.Label lblTotal;
	protected global::System.Web.UI.WebControls.Label lblDeliveryID;
	protected global::System.Web.UI.WebControls.Label lblDeliveryDate;
	protected global::System.Web.UI.WebControls.Label lblStates;
	protected global::System.Web.UI.WebControls.Label lblRemark;


       
    }
}
